name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn install

      - name: Run Build
        run: yarn build

      - name: Run Tests
        run: yarn test

  bump_and_deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Bump Version and Tag
        run: |
          yarn version --patch
          echo "NEW_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV

      - name: Run Build
        run: |
          export NODE_ENV=production
          yarn build

      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@xip.co"
          git add dist
          git commit -m "Automated build for release, version: ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_VERSION }}
          git push --follow-tags
